routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});
Route::get('/configuracion', function () {
    return view('configuracion');
});

Auth::routes();

Route::resource('cuadros', App\Http\Controllers\CuadroController::class)->middleware('auth');
Route::resource('categorias', App\Http\Controllers\CategoriaController::class)->middleware('auth');



Route::get('/home', [App\Http\Controllers\HomeController::class, 'index'])->name('home');
Route::get('/configuracion', [App\Http\Controllers\UsersettingsController::class, 'index'])->name('configuracion');
Route::get('/change/password', [App\Http\Controllers\UsersettingsController::class, 'changePassword'])->name('changePassword');
Route::get('/Catalogo', [App\Http\Controllers\VistacuadrosController::class, 'index'])->name('cuadros');
Route::get('/Sobre Nosotros', [App\Http\Controllers\footer\SobrenosotrosController::class, 'index'])->name('SobreNosotros');
Route::get('/Como funciona', [App\Http\Controllers\footer\FuncionamientoController::class, 'index'])->name('Funcionamiento');
Route::get('/Caracteristicas', [App\Http\Controllers\footer\CatalogoController::class, 'index'])->name('Caracteristicas');
Route::get('/Terminos y condiciones', [App\Http\Controllers\footer\TerminosController::class, 'index'])->name('Terminos');
Route::get('/Envios', [App\Http\Controllers\footer\EnviosController::class, 'index'])->name('Envios');
Route::get('/Contacto', [App\Http\Controllers\footer\ContactoController::class, 'index'])->name('contacto');
Route::get('/Carrito', [App\Http\Controllers\CarritoController::class, 'index'])->name('carrito');
Route::get('/Inicio', [App\Http\Controllers\InicioController::class, 'index'])->name('inicio');

app/Models/Cuadro.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;

/**
 * Class Cuadro
 *
 * @property $id
 * @property $categoria_id
 * @property $nombre
 * @property $created_at
 * @property $updated_at
 *
 * @property Categoria $categoria
 * @package App
 * @mixin \Illuminate\Database\Eloquent\Builder
 */
class Cuadro extends Model
{
    
    static $rules = [
		'categoria_id' => 'required',
		'nombre' => 'required',
    ];

    protected $perPage = 20;

    /**
     * Attributes that should be mass-assignable.
     *
     * @var array
     */
    protected $fillable = ['categoria_id','nombre'];


    /**
     * @return \Illuminate\Database\Eloquent\Relations\HasOne
     */
    public function categoria()
    {
        return $this->hasOne('App\Models\Categoria', 'id', 'categoria_id');
    }
    

}

app/Http/Controllers/CuadroController.php
<?php

namespace App\Http\Controllers;

use App\Models\Cuadro;
use App\Models\Categoria;
use Illuminate\Http\Request;

/**
 * Class CuadroController
 * @package App\Http\Controllers
 */
class CuadroController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $cuadros = Cuadro::paginate();

        return view('cuadro.index', compact('cuadros'))
            ->with('i', (request()->input('page', 1) - 1) * $cuadros->perPage());
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        $cuadro = new Cuadro();
        $categorias = Categoria::pluck('nombre','id');
        return view('cuadro.create', compact('cuadro','categorias'));
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        request()->validate(Cuadro::$rules);

        $cuadro = Cuadro::create($request->all());

        return redirect()->route('cuadros.index')
            ->with('success', 'Cuadro created successfully.');
    }

    /**
     * Display the specified resource.
     *
     * @param  int $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        $cuadro = Cuadro::find($id);

        return view('cuadro.show', compact('cuadro'));
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $cuadro = Cuadro::find($id);
        $categorias = Categoria::pluck('nombre','id');
        return view('cuadro.edit', compact('cuadro','categorias'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request $request
     * @param  Cuadro $cuadro
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, Cuadro $cuadro)
    {
        request()->validate(Cuadro::$rules);

        $cuadro->update($request->all());

        return redirect()->route('cuadros.index')
            ->with('success', 'Cuadro updated successfully');
    }

    /**
     * @param int $id
     * @return \Illuminate\Http\RedirectResponse
     * @throws \Exception
     */
    public function destroy($id)
    {
        $cuadro = Cuadro::find($id)->delete();

        return redirect()->route('cuadros.index')
            ->with('success', 'Cuadro deleted successfully');
    }
}

resources/views/cuadro/create.blade.php
@extends('layouts.app')

@section('template_title')
    Create Cuadro
@endsection

@section('content')
    <section class="content container-fluid">
        <div class="row">
            <div class="col-md-12">

                @includeif('partials.errors')

                <div class="card card-default">
                    <div class="card-header">
                        <span class="card-title">Create Cuadro</span>
                    </div>
                    <div class="card-body">
                        <form method="POST" action="{{ route('cuadros.store') }}"  role="form" enctype="multipart/form-data">
                            @csrf

                            @include('cuadro.form')

                        </form>
                    </div>
                </div>
            </div>
        </div>
    </section>
@endsection

resources/views/cuadro/edit.blade.php
@extends('layouts.app')

@section('template_title')
    Update Cuadro
@endsection

@section('content')
    <section class="content container-fluid">
        <div class="">
            <div class="col-md-12">

                @includeif('partials.errors')

                <div class="card card-default">
                    <div class="card-header">
                        <span class="card-title">Update Cuadro</span>
                    </div>
                    <div class="card-body">
                        <form method="POST" action="{{ route('cuadros.update', $cuadro->id) }}"  role="form" enctype="multipart/form-data">
                            {{ method_field('PATCH') }}
                            @csrf

                            @include('cuadro.form')

                        </form>
                    </div>
                </div>
            </div>
        </div>
    </section>
@endsection

resources/views/cuadro/form.blade.php
<div class="box box-info padding-1">
    <div class="box-body">
        
        


        
        <div class="form-group">
            {{ Form::label('categoria_id') }}
            {{ Form::select('categoria_id',$categorias, $cuadro->categoria_id, ['class' => 'form-control' . ($errors->has('categoria_id') ? ' is-invalid' : ''), 'placeholder' => 'Categoria Id']) }}
            {!! $errors->first('categoria_id', '<div class="invalid-feedback">:message</div>') !!}
        </div>

        <div class="form-group">
            {{ Form::label('nombre') }}
            {{ Form::text('nombre', $cuadro->nombre, ['class' => 'form-control' . ($errors->has('nombre') ? ' is-invalid' : ''), 'placeholder' => 'Nombre']) }}
            {!! $errors->first('nombre', '<div class="invalid-feedback">:message</div>') !!}
        </div>

    </div>
    <div class="box-footer mt20">
        <button type="submit" class="btn btn-primary">Submit</button>
    </div>
</div>

resources/views/cuadro/index.blade.php
@extends('layouts.app')

@section('template_title')
    Cuadro
@endsection

@section('content')
    <div class="container-fluid">
        <div class="row">
            <div class="col-sm-12">
                <div class="card">
                    <div class="card-header">
                        <div style="display: flex; justify-content: space-between; align-items: center;">

                            <span id="card_title">
                                {{ __('Cuadro') }}
                            </span>

                             <div class="float-right">
                                <a href="{{ route('cuadros.create') }}" class="btn btn-primary btn-sm float-right"  data-placement="left">
                                  {{ __('Create New') }}
                                </a>
                              </div>
                        </div>
                    </div>
                    @if ($message = Session::get('success'))
                        <div class="alert alert-success">
                            <p>{{ $message }}</p>
                        </div>
                    @endif

                    <div class="card-body">
                        <div class="table-responsive">
                            <table class="table table-striped table-hover">
                                <thead class="thead">
                                    <tr>
                                        <th>No</th>
                                        
										<th>Categoria</th>
										<th>Nombre</th>

                                        <th></th>
                                    </tr>
                                </thead>
                                <tbody>
                                    @foreach ($cuadros as $cuadro)
                                        <tr>
                                            <td>{{ ++$i }}</td>
                                            
											<td>

                                                {{ $cuadro->categoria->nombre }}
                                            
                                            </td>
                                            <td>{{ $cuadro->nombre }}</td>

                                            <td>
                                                <form action="{{ route('cuadros.destroy',$cuadro->id) }}" method="POST">
                                                    <a class="btn btn-sm btn-primary " href="{{ route('cuadros.show',$cuadro->id) }}"><i class="fa fa-fw fa-eye"></i> Show</a>
                                                    <a class="btn btn-sm btn-success" href="{{ route('cuadros.edit',$cuadro->id) }}"><i class="fa fa-fw fa-edit"></i> Edit</a>
                                                    @csrf
                                                    @method('DELETE')
                                                    <button type="submit" class="btn btn-danger btn-sm"><i class="fa fa-fw fa-trash"></i> Delete</button>
                                                </form>
                                            </td>
                                        </tr>
                                    @endforeach
                                </tbody>
                            </table>
                        </div>
                    </div>
                </div>
                {!! $cuadros->links() !!}
            </div>
        </div>
    </div>
@endsection

resources/views/cuadro/show.blade.php
@extends('layouts.app')

@section('template_title')
    {{ $cuadro->name ?? 'Show Cuadro' }}
@endsection

@section('content')
    <section class="content container-fluid">
        <div class="row">
            <div class="col-md-12">
                <div class="card">
                    <div class="card-header">
                        <div class="float-left">
                            <span class="card-title">Show Cuadro</span>
                        </div>
                        <div class="float-right">
                            <a class="btn btn-primary" href="{{ route('cuadros.index') }}"> Back</a>
                        </div>
                    </div>

                    <div class="card-body">
                        
                        <div class="form-group">
                            <strong>Categoria Id:</strong>
                            {{ $cuadro->categoria_id }}
                        </div>
                        <div class="form-group">
                            <strong>Nombre:</strong>
                            {{ $cuadro->nombre }}
                        </div>

                    </div>
                </div>
            </div>
        </div>
    </section>
@endsection